export default {
    FETCH_JOB_OPTIONS_PENDING: 'FETCH_JOB_OPTIONS_PENDING',
    FETCH_JOB_OPTIONS_SUCCESS: 'FETCH_JOB_OPTIONS_SUCCESS',
    FETCH_JOB_OPTIONS_ERROR: 'FETCH_JOB_OPTIONS_ERROR',
    
    FETCH_TECH_OPTIONS_SUCCESS: 'FETCH_TECH_OPTIONS_SUCCESS',
    FETCH_TECH_OPTIONS_PENDING: 'FETCH_TECH_OPTIONS_PENDING',
    FETCH_TECH_OPTIONS_ERROR: 'FETCH_TECH_OPTIONS_ERROR'
}