export default {
    EDIT_DEV: 'EDIT_DEV',

    SET_INPUT_NAME: 'SET_INPUT_NAME',
    SET_INPUT_JOB: 'SET_INPUT_JOB',
    SET_INPUT_CAREER: 'SET_INPUT_CAREER',
    SET_INPUT_TECH: 'SET_INPUT_TECH',
    RESET_INPUT: 'RESET_INPUT',

    FETCH_DEVS_PENDING: 'FETCH_DEVS_PENDING',
    FETCH_DEVS_SUCCESS: 'FETCH_DEVS_SUCCESS',
    FETCH_DEVS_ERROR: 'FETCH_DEVS_ERROR'

}