export default {
    ADD_DEV: 'ADD_DEV',
    REMOVE_DEV: 'REMOVE_DEV',
    UPDATE_DEV: 'UPDATE_DEV',

    SET_INPUT_NAME: 'SET_INPUT_NAME',
    SET_INPUT_JOB: 'SET_INPUT_JOB',
    SET_INPUT_CAREER: 'SET_INPUT_CAREER',
    SET_INPUT_TECH: 'SET_INPUT_TECH',
    RESET_INPUT: 'RESET_INPUT'

}